
class FungiDictionary{
   
 static nameSplit(String label){
    int id = label.indexOf("_");
    String fungiName = label.substring(id+1).trim();

    int idx = fungiName.indexOf("_");
    String splitFungiName = fungiName.substring(0,idx).trim()+ " "+ fungiName.substring(idx+1).trim();

    return splitFungiName;
  }

  static var info =  {

    '10000_Abortiporus_biennis' : 'Çürüyen odunların üzerinde bulunan bu mantar bazen çok çekici rozetler oluşturur ve bazı insanlar buna Kızarık Rozet adını verir, ancak daha sıklıkla, sonunda kahverengi lekeler bırakmak üzere kuruyan kırmızı-kahverengi sıvı damlacıkları yayan düzensiz labirent benzeri gözeneklerden oluşan amorf bir kütle olarak büyür.',
    '10056_Agaricus_arvensis' : 'At mantarı olarakta bilinen iyi bir yenilebilir çayır mantarı türüdür. Tadı ayırt edici değildir. Fakat kokusu ayırt edici özellik kabul edilir ve yoğun anason kokar.',
    '10057_Agaricus_augustus' : 'Dünya literatürlerinde “Prince” yani Prens olarak bilinen Agaricus augustus, göze hoş gelen, güzel bir görüntüsü olduğu için Prens olarak isimlendirilmiştir. Kaliteli yenilebilir mantarlar gururundadır. Ülkemizde bilinen ismi Şehzade mantarıdır.',
    '10158_Aleuria_aurantia' : 'Zehirli bir tür değildir ancak pek tadı olmamasından ve besin değeri düşük olduğu için pek tüketilmemektedir. Orange peel fungus (Portakal Kabuğu Mantarı), parlak turuncu, fincan şeklindeki ascocarps hali , yere serpilmiş portakal kabuklarına benzer ve bu türe ortak adını verir. Portakal Kabuğu Mantarı, İskandinavya’dan İber Yarımadası’nın güney kıyılarına Avrupa’nın hemen hemen her yerinde ve Kuzey Amerika’da sıkça rastlanılan bir türdür. ',
    '10225_Amanita_ceciliae' : 'Yılan derisi grisette (Snakeskin grisette) ve boğulmuş Amanita (Strangulated Amanita) olarak adlandırılan Amanita ceciliae, Amanita cinsinde bir basidiomycete mantarıdır. Diğer yüzüksüz Amanita’ların aksine, bu tür biraz zehirli kabul edilir. Yenilebilirliliği hakkında geniş bilgi yoktur.',
    '10230_Amanita_excelsa' : 'Bazı yetkililer bu temiz ama kasvetli görünümlü mantarların lezzet açısından özel bir şey olmamasına rağmen yenilebilir olduğunu iddia eder. Bu büyük, gri ila kahverengi arası şapkalı mantar değişken bir görünüme sahiptir. Avrupa ve Kuzey Amerika’daki iğne yapraklı ve yaprak döken ormanlarda yaygın olarak görülür.',
    '10234_Amanita_fulva' : 'Her ne kadar iyi pişirildiğinde toksinleri yok olsa da yenilmesi önerilmemektedir. Sıklıkla Avrupa’nın yaprak döken ve iğne yapraklı ormanlarında ve Kuzey Amerika’da bulunan bir mantar türüdür.',
    '10252_Amanita_muscaria' : 'Sinek mantarı (Amanita muscaria), Gelin mantarı olarak da bilinen, Amanitaceae familyasından çok zehirli ve halüsinojen bir mantar türüdür. Yarattığı delilik krizleri 4-6 saat sürer. Bu mantardan etkilenenlerde; ruh halinin değişmesi, (keyifli veya kaygılı durum), nedensiz gülme, hayal görme, konuşma güçlüğü, kas spazmları, görme ve işitme bozukluğu, yorgunluk gibi belirtiler görülür. Bu mantardan zehirlenmelerde ölüm olayı nadirdir, özellikle küçük çocuklarda tehlikeli olabilmektedir.',
    '10257_Amanita_pantherina' : 'Sinek mantarına (Amanita muscaria) çok benzeyen halüsinojen ve zehirli bir mantar türüdür. Çok miktarda mantar zehirlenmesinden sorumludur. İlkbahardan sonbahara kadar bulunabilir. Büyük, gösterişli ve hoş kokuludur. Genelde çocuklar ve hayvanlar tarafından kazara yense de, bazen yetişkinler halüsinojen etkileri için tüketirler. Amanita muscaria(sinek mantarı) nazaran çok daha etkili ve zehirli bir mantardır.',
    '10258_Amanita_phalloides var. phalloides' : 'Türkiyede Köygöçüren adıylan bilinen zehirli bir mantar türüdür. Türkiye\'deki ölümcül zehirlenmelerin neredeyse %90 kadarından sorumlu, son derece zehirli ve tehlikeli bir mantardır. Bu mantara yaz başlarında ve sonbahar aylarında ormanlarda çok sık rastlanır.',
    '10266_Amanita_strobiliformis' : 'Yenilebilirliği konusunda farklı görüşler vardır. Bazı kaynaklar onları tüketmemeye karşı tavsiyede bulunurken, diğer kaynaklar onları yenilebilir olarak kabul eder.',
    '10273_Amanita_virosa' : "Ölüm meleği olarak da bilinir , Amanitaceae ailesinden öldürücü derecede zehirli bir mantar türüdür. Kesinlikle yiyeceklerle birlikte tutulmaması gerektiği önerilir. Amanita virosa beyaz, kenarları beyaz ortası sarımsı veya pembemsi bir şapkaya sahiptir. Mantarın ilk oluştuğunda onu taşıyan beyaz bir yumurtaya benzeyen kapsülü karakteristiktir, genç örnekleri yenebilen diğer mantarlarla karıştırılabilir. Genelde Ağustos'tan Kasım'a kadar ormanlarda bulunabilir, kokusu hoş değildir.",
    "10440_Antrodiella_serpula" : "Zehirlidir ve yenmeye uygun bir mantar türü değildir. Daha çok ağaç ve odun gövdeleri üzerinde bulunurlar.",
    "10526_Armillaria_mellea" : "Armillaria mellea, yaygın olarak bal mantarı olarak bilinir. Armillaria mellea mantarı, bazıları tarafından tercih edilmese de yenilebilir olarak kabul edilir ve sert sapları genellikle ayıklanır. Bazı kişiler mide rahatsızlıklarına neden olan \"alerjik\" reaksiyonlar bildirmiştir.",
    "10667_Ascocoryne_sarcoides" : "Halk arasında jöle damlaları veya mor jöleler olarak bilinen bu yaygın mantar, jelatinimsi pembemsi veya mor renkli diskler kütlesi olarak görünür. Yenilmeye uygun olmayan bir mantar türüdür. Kuzey Amerika, Avrupa ve Asya'da yaygın olarak dağıtılan saprobik bir mantardır ve çeşitli ölü ağaçların gövde ve dallarında kümeler halinde yetişir.",
    "10934_Auricularia_auricula-judae" : "En yaygın olarak ahşap kulak veya siyah ahşap kulak olarak bilinen, dünya çapında bulunan yenilebilir bir Auriculariales mantarı türüdür. İlaç yapımında da kullanılmaktadır. Genelikle mürver olmak üzere ağaç gövdelerinde yetişmektedir.",
    "10940_Auriscalpium_vulgare" : "Yaygın olarak çam kozalağı mantarı, koni dişi veya kulak toplama mantarı olarak bilinir. Sert dokusu nedeniyle genellikle yenilebilir olarak kabul edilmez, ancak bazı tarihsel literatür, Fransa ve İtalya'da tüketildiğini söylemektedir. Avrupa, Orta Amerika, Kuzey Amerika ve ılıman Asya'da yaygın olarak bulunmaktadır. Yaygın olmasına rağmen, küçük boyutu ve sıradan renkleri, yetiştiği çam ormanlarında kolayca gözden kaçmasına neden olur.",
    "10969_Baeospora_myosura" : "Zehirsiz olarak kabul edilen bu mantar, bitki materyali ve gübre üzerinde yetişir. Krem beyazdır ve spor rengi beyaz, krem veya sarımsıdır. Kuzey Amerika ve Avrupa'da yaygın olarak bulunur.",
    "10994_Basidioradulum_radula" : "Diğer kabuk mantarlarında olduğu gibi sert ve yenmeyen bir mantardır. Bu soluk renkli kabuk mantar düşmüş bir dalın neredeyse tüm yüzeyini kaplayan düzensiz yamalar oluşturmak üzere birleşir. Bu kabuk mantarı, ölü yaprak döken sert ağaçları tüketir.",
    "11043_Bjerkandera_adusta" : "Bjerkandera adusta, yaygın olarak dumanlı polipor veya dumanlı braket olarak bilinir. Yemek için uygun bir mantar değildir. Canlı ağaçlarda beyaz çürümeye neden olan bir bitki patojenidir, ancak en yaygın olarak ölü ağaçta görülür.",
    "11054_Bolbitius_titubans" : "Bolbitius vitellinus olarak da bilinen Bolbitius titubans, Amerika ve Avrupa'da bulunan yaygın bir mantar türüdür. Esas olarak gübre veya yoğun gübrelenmiş toprakta ve bazen de çimenlerde yetişir. Zehirsizdir.",
    "11062_Butyriboletus_appendiculatus" : "Yenilebilir ve çeşitli kaynaklar tarafından tercih edilmektedir, ancak bazıları bazı kişilerin buna alerjik reaksiyon gösterebileceği konusunda uyarıda bulunur. Mantarların topraksı aroması onları çorbalara, soslara ve yahnilere uygun hale getirir. Meşe ve kayın gibi diğer geniş yapraklı ağaçların altında yetişen yenilebilir gözenekli bir mantardır.",
    "11202_Buglossoporus_quercinus" : "Yemek için uygun bir mantar değildir. Sert ve kabukludur.",
    "11206_Bulgaria_inquinans" : "Genellikle kara bulgar ve kara jöle damlaları adıyla bilinir. Zehirli etki sahiptirler. Ölü meşe ve gürgen dallarında ve kabuklarında yetişir. Ayrıca kül geri tepme hastalığı nedeniyle dişbudak ağaçlarında da yetiştirilmektedir. Türler Ekim'den Mart'a kadar bulunabilir.",
    "11234_Calocera_viscosa" : "Zehirli değildir, ancak sert jelatinimsi dokusu ve tarifsiz tadı ve kokusu onu bir yiyecek olarak çekici yapmaz. Ancak çarpıcı rengi, zaman zaman garnitür olarak kullanılmasına neden olmuştur. Genellikle sarı geyik boynuzu olarak bilinen Calocera viscosa, benzersiz \"ayar çatalı\" bazidiaları ile karakterize edilen bir mantar düzeni olan Dacrymycetales'in bir üyesi olan bir jöle mantarıdır.",
    "11237_Calocybe_gambosa" : "Genellikle St. George mantarı olarak bilinen Calocybe gambosa, esas olarak tarlalarda, çimen kenarlarında ve yol kenarlarında yetişen yenilebilir bir mantardır. Bu Mantar en iyi kuru havalarda toplanmaktadır. Kuru, salamura ve hatta çiğ olarak yenebilir. Romanya'dan Batı Avrupa'ya ticari miktarlarda ithal edilmektedir. Ortak adını Birleşik Krallık'ta ilk göründüğü zamandan, yani St George Günü'nden (23 Nisan) alır. Ticari değeri yüksek ve talep gören bir mantar türüdür.",
    "11314_Cantharellus_amethysteus" : "Yenilebilir popüler mantar Cantharellus cibarius ile çok yakından ilişkili ve eşit derecede lezzetli olan bu mor veya menekşe tonlarında Cantharellus cibarius, İngiltere'de ve genellikle sert ağaçların, özellikle meşe ağaçlarının altında yetiştiği Avrupa'nın başka yerlerinde nadiren bulunur.",
    "11317_Cantharellus_cibarius" : "Yenebilir bir mantar türüdür. Avrupa'dan Akdeniz boyunca İskandinavya'ya özellikle yaprak döken ve çamlık ormanlarda bulunur.  Rengi sarıdan koyu sarıya doğru çeşitlilik gösterebilir. Aroması ve kokusu kayısıyı andırır.",
    "11384_Ceratiomyxa_fruticulosa" :"Küçük, dik, dallı veya basit yapılara sahip beyazımsı ve yarı saydam bir yapıları vardır. Bir mercana veya küçük, dik buz sarkıtlarına benzer. Sporlarını dış yüzeylerinde ürettikleri için bulanık bir görünüme sahiptirler. Yemek için uygun değildir.",
    "11573_Chalciporus_piperatus" : "Yaygın olarak peppery bolete olarak bilinen Chalciporus piperatus, Avrupa ve Kuzey Amerika'da karışık ormanlık alanlarda bulunan Boletaceae familyasının küçük gözenekli bir mantarıdır. İyice pişirildiğinde yenilebilir olduğu bildirilmektedir, ancak çok biberlidir ve muhtemelen en iyi diğer mantar yemeklerini tatlandırmak için kullanılır.",
    "11600_Chlorociboria_aeruginascens" : "Gerçek meyve gövdeleri nadiren görülse de, mantarın neden olduğu ahşabın yeşil lekelenmesi daha yaygındır. Zehirli bir etkiye sahiptir.",
    "11711_Clavariadelphus_pistillaris" :"Türün yenilebilir olduğu kaydedilmiştir. Avrupa ve Kuzey Amerika'ya özgü Gomphaceae familyasının nadir bir mantar türüdür. Yaz ve sonbaharda neredeyse sadece kayın ormanlarında, kireçli topraklarda çöp ve talaşlar üzerinde yetişir.",
    "11912_Conocybe_albipes" : "Hem Kuzey Amerika'da hem de Avrupa'da kısa yeşil çimenler arasında yetişen oldukça yaygın bir mantardır. Yakın zamana kadar, tür yaygın olarak Conocybe lactea veya Conocybe albipes olarak da adlandırılıyordu ve halk dilinde beyaz aptal şapka olarak biliniyordu. Bazı Conocybe türlerinin  ölümcül toksinleri içerdiği bilinmektedir ve bu nedenle Conocybe apala muhtemelen en iyi şekilde 'şüpheli' kabul edilir ve çim biçme makinesine bırakılır.",
    "12750_Craterellus_cornucopioides" : "Borazan Mantarı ya da Bol Boynuz olarak bilinen bu mantar görünüşü kasvetli olsada yenilebilen bir mantardır. Mantar gövdeleri, yaprak döken ağaçların altında toprakta büyür. Sert yapıları ve eti vardır. Bu nedenle kurtçuklar tarafından kolay istila edilemezler. Kış aylarında rahatlıkla bulunabilen güzel bir mantar türüdür.",
    "12763_Hericium_cirrhatum" : "yüksektir. Gençken kokusu belirli değildir ancak çürümeye başladığında mide bulandırıcı bir koku yayar.",
    "12918_Cyathus_striatus" : "Türkiye’de Dikenli Çizgiliyuva Mantarı olarak Çatalca -Kocaeli Bölümü, Karadeniz Bölgesi ve Yukarı Sakarya Bölümünde kaydı yapılmış, tıbbi açıdan büyük önem arz eden enterasan görüntüsü ile ilgi çeken bir mantardır. Yenmeyen bir mantar türü olduğu bildirilmektedir.",
    "12956_Cystolepiota_seminuda" : "Yenmeyen, yaygın bir mantarıdır. Humusta, genellikle orman yollarında bulunur. Diğer lepiotoid mantarlar gibi, sapsız solungaçlara ve beyaz bir spor baskısına sahiptir.",
    "13002_Daedalea_quercina" : "Avrupa, Asya, Kuzey Afrika ve Avustralasya'da bulunur. Yenmeyen bir bitki olmasına rağmen doğal tarak olarak kullanılabilir ve kimyasal araştırmalara konu olmuştur.",
    "13007_Daldinia_concentrica" : "Yenmeyen mantar Daldinia concentrica, Kral Alfred'in keki, kramp topları ve kömür mantarı da dahil olmak üzere birçok yaygın adla bilinir. Diğer mantarlarda olduğu gibi, hafif sporlar küresel olarak dağılır ve mantarlar, koşulların uygun olduğu her yerde gelişir.",
    "13361_Disciotis_venosa" : "Yenilebilir bir türdür. Ancak bir yazar, diğer birkaç kahverengi kap mantarıyla karıştırılabileceğinden, yalnızca mikroskobik karakterlerini kontrol edecek donanıma sahip koleksiyoncuların türleri tüketmeyi düşünmesi gerektiğini belirtmiştir. Nisan ve Mayıs aylarında meyve verirler, genellikle koyu kahverengi renklerinden dolayı yerlerini bulmak zordur. Kuzey Amerika ve Avrupa'da bulunurlar.",
    "13625_Entoloma_incanum" : "Zehirli bir mantardır ve yemek için toplanmaz. Yeşilimsi gövdesi ve kafesteki fareyi andıran kokusuyla Entoloma incanum, tarlada güvenle tanımlanabilen birkaç küçük mantardan biridir. İngiltere ve İranlada'da az görülmesine rağmen kıta avrupası ve Kuzey Amerikada yaygın olarak bulunmaktadır.",
    "13764_Entoloma_sericeum var. sericeum" : "Bazı alan rehberlerinde yenmez olduğu bildirilen bu mantar türü ile ilgili net bir bilgi yoktur. Bu mantar türü ailesinde bulunan bazı türler çok zehirliği olduğu için bu türden de uzak durulması tavsiye edilmektedir.",
    "13765_Entoloma_serrulatum" : "Bazı saha rehberlerinde yenmez, bazılarında ise zehirli olduğu bildirilen bir mantardır. Güney Britanya, İrlanda ve güney anakara Avrupa'da nadiren görülen bu pembe yaprak, İskoçya ve İskandinavya'da oldukça yaygındır. Mavi-siyah, bir mantar için alışılmadık bir renktir ve genellikle merkeze yakın ince pullara ayrılan radyal fibriloz başlık, bu sevimli Entoloma'yı diğer mavimsi türlerden ayırmaya yardımcı olur.", 
    "14032_Fistulina_hepatica" : "Yenebilen bir mantar türüdür. Tadı, ekşimsi ve hafif asidiktir. Genelde canlı ve çürümüş ağaçlarda yetişir. Çınar ve kestane ormanlarında oldukça sık rastlanır. Avustralya'da okaliptüs ağaçlarının yaralanmış yerlerinde yetişir.",
    "14056_Flammulina_velutipes var. velutipes" : "Kış mantarı olarakta bilinen, uzun ve beyaz bir mantar türüdür. Mantar, hackberry ağacının kütüklerinde, kül, dut ve hurma ağacı gibi diğer ağaçlarda doğal olarak yetişmektedir. Mantar, özellikle Uzak Doğu mutfaklarında kullanılmaktadır. Geleneksel olarak çorbalarda kullanılır, ancak salatalar ve diğer yemekler için de kullanılabilir. Mantarın gevrek bir dokusu vardır ve yaklaşık bir hafta boyunca soğutulabilir.",
    "14073_Fuligo_septica" : "Bir balçık küfü türüdür ve Myxomycetes sınıfının bir üyesidir. Özel sarımsı, safra rengi görünümünden dolayı genellikle çırpılmış yumurta sümüksü veya ten rengi çiçekler[2] olarak bilinir. Aynı zamanda köpek kusmuğu balçık küfü olarak da bilinir ve dünya çapında bir dağılımla nispeten yaygındır. Zehirli etkisi olmasada yenilmemektedir.",
    "14190_Geastrum_michelianum" : "Dünya yıldızları olarak bilinen bu mantarlar yenmez ve mutfak değeri yoktur. Dünyayıldızları çoğunlukla sert ağaçların altında bulunur, ancak  özellikle köknar ve ladinlerle birlikte iğne yapraklı ormanlarda da görülmektedir.", 
    "14208_Geoglossum_fallax" : "Bu kasvetli toprak dili, esas olarak hassas bir şekilde yönetilen eski kilise bahçeleri gibi yosunlu, gelişmemiş çayırlarda bulunur. Zehirli değildir.", 
    "14394_Grifola_frondosa" : "Japoncosı maitake(dans eden mantar) olan bu tür zehirli  değildir. Genellikle yaz sonundan sonbahar başlarına kadar bulunur. Çin, Avrupa ve Kuzey Amerika'ya özgüdür.",
    "14422_Gymnopilus_spectabilis" : "Esas olarak halüsinojenik özellikleri ile bilinmesine rağmen, tıp alanında da bu mantarı kullanılarak bazı araştırmalar yapılmaktadır. Uzak durulması tavsiye edilir.", 
    "14435_Gymnopus_dryophilus" : "Bazı saha rehberlerinde yenilebilir ama buna değmez olarak kaydedilir, ancak her durumda, gövdeler kesinlikle baştan çıkarılamayacak kadar sertken başlık eti çok ince ve önemsizdir.Bu nedenle bir mutfak değeri yoktur.",
    "14454_Gyromitra_esculenta" : "Kuzu Göbeği Ebesi, ilginç şekliyle ve ölümcül, zehirli toksinler ihtiva etmesiyle mantar avcılarının çok iyi tanıması gereken bir türdür. Avrupa ve Kuzey Amerika'da yaygın olarak görülmektedir. Türkiye'de de sıklıkla görülebilmektedir.", 
    "14607_Helvella_crispa" : "Beyaz Semer Mantarı olarakta bilinen tür bazı rehber kitablarında yenilebilir olarak listelense de şiddetli zehirlenmeye neden olabilen ve kanserojen olan maddeler bulundurduğuna dair spekülasyonlar vardır. Çiğ yenildiğinde gastrointestinal semptomlara neden olduğu bildirilmiştir.",
    "14615_Helvella_lacunosa" : "Bu tür, pişirildikten sonra yenir ve bazıları tarafından çok beğenilir, ancak sapları yenmez. Çiğ yenildiğinde gastrointestinal semptomlara neden olduğu bildirilmiştir. Az miktarda monometilhidrazin toksini içerebilir, bu nedenle pişirme gereklidir. Roger Phillips buna \"yenilebilir ama değmez\" demiştir.",
    "14667_Hericium_coralloides" : "Genellikle mercan dişi mantarı olarak bilinen saprotrofik bir mantardır. Ölü sert ağaçlarda yetişir. Tür gençken yenilebilir ve iyidir, ancak yaşlandıkça dallar ve sarkan dikenler kırılgan hale gelir ve açık sarımsı kahverengi bir tona dönüşür. Zehirli değildir ve yenebilir.",
    "14798_Hydnum_repandum" : "Genellikle tatlı diş, tahta kirpi veya kirpi mantarı olarak bilinen bu tür; tatlı, cevizli bir tada ve gevrek bir dokuya sahip, iyi bir yenilebilir olarak kabul edilir. Bazıları onu Cantharellus cibariusun mutfaktaki eşdeğeri olarak görür.",
    "14822_Hygrocybe_cantharellus" : "Bazı alan rehberlerinde yenilebilir oldukları bildirilse de, bu küçük mum kapakları o kadar önemsizdir ki yenilebilir bir değerleri yoktur. İyileştirilmemiş yosunlu otlaklarla sınırlı olan Hygrocybe cantharellus, İngiltere ve İrlanda'da az görülen ancak nadir bir tür değildir ve kıta Avrupa'nın bazı bölgelerinde de görülür.",
    "14833_Hygrocybe_conica var. conica" : "Yaygın olarak cadı şapkası, konik mum başlığı veya konik yapışkan başlık olarak bilinir, kuzey Avrupa ve Kuzey Amerika'da bulunan Hygrocybe (balmumu kapakları) cinsinin renkli bir üyesidir. Başlangıçta Hygrophorus conicus olarak tanımlanan bu, yakından ilişkili ve benzer türlerin bir kompleksi olabilir. Zehirli etkiler gösterebilir.",
    "14861_Gliophorus_psittacinus" : "Genellikle yenilebilir olarak kabul edilir, ancak küçük boyutu ve inceliği nedeniyle buna değmez. Bir oturuşta 20'den fazla örneğin tüketilmesi gastrointestinal rahatsızlıklara neden olabilir. Batı Avrupa, Birleşik Krallık, İzlanda, Grönland, Amerika, Güney Afrika, Japonya'daki otlaklarda yaygın olarak bulunur ve yaz sonu ve sonbaharda bulunur.",
    "14863_Hygrocybe_punicea" : "Bazen kıpkırmızı veya kırmızı mumsu başlık olarak da adlandırılır, Kuzey Avrupa'da bulunan mum kapakları olan Hygrocybe cinsinin renkli bir üyesidir. Başlangıçta Hygrophorus puniceus olarak tanımlanan cinsin en büyük üyesidir. Kuzey Amerika'da advers reaksiyon raporları olmasına rağmen, hafif tadı olan tür, Avrupa'da yenilebilir olarak kaydedilmiştir. Bazıları mide-bağırsak rahatsızlığına neden olduğunu bildirmiştir.",
    "15078_Hypholoma_fasciculare" : "Ormanlık alanlarda sıklıkla görülen bir mantardır. Geniş yapraklı ağaçların (meşe, kayın, vb.) ölü kökleri ya da çürüyen gövdelerinde büyük kümeler halinde görülür. Acı ve zehirli bir mantardır. Tüketilmesi kusma, ishal ve kasılmalara neden olabilir.",
    "15624_Laccaria_amethystina" : "Yaprak döken ve iğne yapraklı ormanlarda yetişen küçük, parlak renkli bir mantardır. Mantarın kendisi yenilebilir, ancak topraktan arsenik emebilir. Doğal olarak toksik olmasa da, arsenikle kirlenmiş topraklarda bu elementin yüksek konsantrasyonunu biyolojik olarak biriktirebilir.", 
    "16105_Leccinum_quercinum" : "Boletus Meşesi olarak bilinen bu mantar, Avrupa'da genellikle iyi bir yenilebilir mantar olarak kabul edilir. En sık kavak ağaçlarının ve titrek kavakların altında görünen ama aynı zamanda meşe, kayın ve huş ağaçlarının altında da kaydedilmiştir.", 
    "16723_Marasmius_rotula" : "Marasmius rotula genellikle yenmez olarak kabul edilir, ancak zehirli değildir. Mantarın belirgin bir kokusu yoktur ve tadı yavan ya da acı olarak değişir. uzey Yarımküre'de yaygın olarak bulunur, genellikle fırıldak mantarı, fırıldak marasmius, küçük tekerlek, yakalı paraşüt veya at kılı mantarı olarak bilinir.", 
    "16907_Meripilus_giganteus" : "Çok kaba eti ve hafif asidik tadı nedeniyle önceden yenmez olarak kabul edilirdi, ancak daha yeni kaynaklar onu yenilebilir olarak listelemektedir. Genç örnekleri daha lezzetli olabilir ve bir yazar Japonya'da yendiğini de belirtmektedir.",
    "17041_Mitrula_paludosa" : "Bataklık feneri olarak adlandırılan bu mantar türü çok küçük ve yenilmeyen bir türdür. bu küçük mantar çok ıslak yerlerde meydana gelmektedir. Doğal dünyadaki rolü, geri dönüştürücünün rolüdür; çürüyen yapraklardan ve gövdelerden beslenirler, onları diğer bitkilerin besleyebileceği basit bileşiklere ayırmaya yardımcı olurlar.", 
    "18328_Phaeolepiota_aurea" : "Çeşitli yemek kitapları, güzel tadı için bu mantarı tavsiye etmektedir. Ancak Daha sonraki çalışmalar, meyve gövdesinin kabul edilemez miktarlarda hem kadmiyum hem de siyanür bileşikleri içerdiğini göstermiştir. Bu nedenle, mantar artık yenilebilir olarak kabul edilmez. Pişirme, mevcut siyanür bileşiklerinin konsantrasyonunu azaltır. Bu, Phaeolepiota aurea'nın yenilebilir olarak kabul edilmesinin nedeni olabilir.", 
    "18484_Pholiota_flammans" : "Pholiota flammans meyve gövdeleri belirgin bir kokuya sahip değildir ve tadı hafif ila hafif acıdır. Zehirli olmamasına rağmen bazı yazarlar mantarı yenmez olarak görürken, diğerleri onu yenilebilir veya yenilebilirliği bilinmeyen olarak değerlendirir. Kuzey ve ılıman bölgelerde Avrupa, Kuzey Amerika ve Asya'da yayılış gösterir. Yenilebilirliği açıklığa kavuşturulmamıştır.", 
    "19213_Pseudoclitocybe_cyathiformis" : "Tüm otoriteler bunu yenilebilir bir mantar olarak listelemese de, kasvetli görünümüne rağmen, Kadeh mantarının iyice pişirilmesi şartıyla yemek için oldukça iyi olduğu yaygın olarak bilinir. (Sapları çok serttir ve kesinlikle atılmalıdır.) Bununla birlikte, bazı kişilerin bu türü yedikten sonra ters tepkiler yaşadığına dair raporlar vardır ve bu nedenle, onları ilk kez deneyecekseniz çok küçük bir kısmı tüketilmelidir.",
    "19549_Pycnoporellus_fulgens" : "Avrasya ve Kuzey Amerika'ya özgü olan bu mantar yemek için uygun değildir.", 
    "19653_Ramaria_botrytis" : "Yenilebilir bir türdür ve bazıları onu güzel olarak değerlendirir. Tadı \"hafif\" veya \"meyvemsi\"dir ve lahana turşusuna, yeşil fıstıklara (kurutulmamış taze hasat edilmiş fıstıklar) veya bezelyelere benzetilmiştir. Daha yaşlı meyve gövdeleri asidik bir tat geliştirir. Japonya'daki gıda pazarlarında Nedzumi-take olarak satılmakta ve Kore ve Nepal'de doğadan hasat edilmektedir.",
    "19975_Russula_fragilis var. fragilis" : "Bu mantar içerdiği toksinler ve çok acı tadı nedeniyle yenmez. Birçok Russula türü, tüketildiğinde mide-bağırsak yapısı sorunlarını ortaya çıkararak ishal ve kusmaya neden olur. Avrupa, Asya ve Kuzey Amerika'da karışık ormanlarda ve ormanlarda bulunan küçük, kırılgan, uzun saplı ve değişken renkli bir gevrekdir.",
    "20171_Sarcoscypha_austriaca" : "Genellikle kızıl elf kupası olarak bilinir. Tür adı \"Avusturya'dan\" anlamına gelir. Zehirli bir tür değildir.",
    "20216_Scleroderma_areolatum" : "Genellikle yaprak döken ormanlarda, nötr toprakta bulunurlar. Zehirlidirler ve yutulması kusmaya, ishale ve daha büyük miktarlarda bayılmaya neden olabilir. Dışarıdan farklı mantar türleri ile kırıştırsalarda ortadan ikiye yarınca kendilerini çok net belli ederler.", 
    "20734_Suillus_luteus" : "Yenilebilir bir mantardır, ancak slime/pileipellis çıkarılmalıdır. Bazı yazarlar onu düşük kaliteli görse de, tür Slav kültürlerinde bir incelik olarak kabul edilir. Lehçe, \"tereyağı\" anlamına gelen kelimelerden türetilmiştir.",
    "20897_Thelephora_terrestris" : "Basidiomycota filumunda bulunan yenmeyen bir mantar türüdür. Dairesel ve üst üste binen kapağı nedeniyle yaygın olarak Ortak Elyaf Vazo adıyla bilinir. Ayrıca Earthfan mantarı olarak da adlandırılır.", 
    "21698_Volvariella_bombycina" : "Meyve gövdeleri yenilebilir ve genellikle kaliteli olarak kabul edilir. Bunlar \"mükemmel\", \"mütevazı ve hoş bir tada\" sahip \"lezzetli\" ve \"yeterli miktarda bulunursa yemeye değer\" olarak adlandırılmıştır. Ülkemizde ve Asya, Avustralya, Karayipler, Avrupa ve Kuzey Amerika’dan varlığı bildirilmiştir."

  };



  static List<String> poisonousMushrooms = [

    '10252_Amanita_muscaria', '10257_Amanita_pantherina', '10258_Amanita_phalloides var. phalloides',
    '10273_Amanita_virosa', "10440_Antrodiella_serpula", "11206_Bulgaria_inquinans", "11600_Chlorociboria_aeruginascens",
    "13625_Entoloma_incanum", "13765_Entoloma_serrulatum", "14422_Gymnopilus_spectabilis",
    "14454_Gyromitra_esculenta", "14607_Helvella_crispa", "14833_Hygrocybe_conica var. conica", "15078_Hypholoma_fasciculare",
    "15624_Laccaria_amethystina", "18328_Phaeolepiota_aurea", "19213_Pseudoclitocybe_cyathiformis", "19975_Russula_fragilis var. fragilis", 
    "20216_Scleroderma_areolatum"
  ];

  static List<String> notEdibleMushrooms =[
      '10000_Abortiporus_biennis', "10667_Ascocoryne_sarcoides", "10940_Auriscalpium_vulgare",
      "10994_Basidioradulum_radula", "11043_Bjerkandera_adusta", "11202_Buglossoporus_quercinus",
      "11384_Ceratiomyxa_fruticulosa", "12918_Cyathus_striatus", "12956_Cystolepiota_seminuda",
      "13002_Daedalea_quercina", "13007_Daldinia_concentrica", "14073_Fuligo_septica", 
      "14190_Geastrum_michelianum", "14435_Gymnopus_dryophilus", "14822_Hygrocybe_cantharellus",
      "16723_Marasmius_rotula", "17041_Mitrula_paludosa", "19549_Pycnoporellus_fulgens",
      "20897_Thelephora_terrestris"
  ];

  static List<String> unknownMushrooms=[
      '10234_Amanita_fulva', '10266_Amanita_strobiliformis', "10969_Baeospora_myosura",
      "11912_Conocybe_albipes", "13764_Entoloma_sericeum var. sericeum", "18484_Pholiota_flammans"

  ];
}